# ----
# Site

title: Treat Template
url: "https://apothecarymark.github.io/food-blog"
baseurl:
google_analytics_key:
newsletter_action:
disqus_shortname:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Food blog template for Jekyll.
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name: Treat Template
  links:
    - https://github.com/CloudCannon/treat-jekyll-template

# -----
# Build

timezone: Etc/UTC

paginate: 10
paginate_path: "/:num/"
permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      push_sidebar_down: true
      print_stylesheet: true
      comments: true
      _options:
        content:
          width: 1560
          height: 2000
        featured_image:
          width: 1560
          height: 2000
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"
      push_sidebar_down: true

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

social_icons:
 # - Facebook
 # - Google Plus
 # - Instagram
 # - LinkedIn
 # - Pinterest
 # - Tumblr
 # - Twitter
 # - YouTube
  - RSS

_options:
  author_image:
    width: 400
    height: 400
    
prose:
  metadata:
    _includes:
      - name: "title"
        field:
          element: "hidden"
          label: "title"
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          value: true
    contact.md:
      - name: "subtitle"
        field:
          element: "text"
          label: "subtitle"
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "hidden"
          value: "/contact"
    about.md:
      - name: "subtitle"
        field:
          element: "text"
          label: "subtitle"
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "hidden"
          value: "/about"
    _posts:
      - name: "date"
        field:
          element: "hidden"
          value: CURRENT_DATETIME
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "subtitle"
        field:
          element: "text"
          label: "subtitle"
      - name: "layout"
        field:
          element: "hidden"
          label: "layout"
      - name: "categories"
        field:
          element: "hidden"
          label: "categories"
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          value: true
  media: "img"
  ignore:
    - /_sass
    - /_includes/category
    - /_includes/externals
    - /_includes/meta_tags
    - /_includes/page
    - /_includes/post
    - /_includes/header.html
    - /_layouts
    - /images
    - /js
    - /img
    - /assets
    - /css
    - /categories
    - CNAME
    - sitemap.xml
    - feed.xml
    - readme.html
    - README.md
    - .gitignore
    - robots.txt
    - 404.html
    - index.html
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - apple-touch-icon.png
    - touch-icon.png
    - contact-success.html
    - siteicon.png
    - config.yml
